kubeEtcd:
  service:
    port: 2381
    targetPort: 2381
nodeSelector:
  kubernetes.io/role: master
tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Equal"
    effect: "NoSchedule"